#!/usr/bin/env python3
"""Generate the data the site's interactive pages render, and the home hero.

The landing page, the course map and the concept atlas all display figures --
how many lessons sit in each stage, how long the course is, which concepts
recur. Every one of those is a countable property of `syllabus.yml`, the lesson
frontmatter and `concepts/graph.json`, so none of them may be typed into a
template or a script. This is the fourth generated view of the course, after
SYLLABUS.md, the graph blocks and the mkdocs nav.

Two outputs, both committed and both covered by --check:

  docs/assets/data/site.json          read by the map and atlas at runtime
  overrides/partials/hero-stats.html  included by main.html at BUILD time

The hero is a rendered partial rather than a client-side fetch on purpose. Its
whole job is to show the thesis -- half the course is evolve and govern, a ninth
is retrieve -- and a number that flashes in after paint, or is missing entirely
without JavaScript, is not showing it.

    uv run python tools/build_site_data.py            # write both
    uv run python tools/build_site_data.py --check    # fail if either is stale
"""
from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from _common import ROOT, concepts, lessons, syllabus, syllabus_lessons

GRAPH = ROOT / "concepts" / "graph.json"
DATA_OUT = ROOT / "docs" / "assets" / "data" / "site.json"
HERO_OUT = ROOT / "overrides" / "partials" / "hero-stats.html"
STRIP_OUT = ROOT / "overrides" / "partials" / "lesson-strip.html"
ROAD_OUT = ROOT / "overrides" / "partials" / "roadmap.html"
MODULES_DIR = ROOT / "modules"

BEGIN = "<!-- site:begin -- generated by tools/build_site_data.py -->"
END = "<!-- site:end -->"

# The stages whose share of the course *is* the argument the course makes.
WRITE_PATH_STAGES = ("evolve", "govern")
# A concept is "touched" by a lesson that teaches it or uses it. Counting only
# `uses` undercounts every concept by its own home lesson.
TOUCH_KINDS = ("teaches", "uses")


def _test_counts() -> dict:
    """Two honest numbers, because they answer different questions.

    `functions` counts `def test_` in the tree. `cases` is what pytest actually
    runs, which is larger because parametrised tests expand. Quoting one while
    meaning the other is how "823 tests" and "757 tests" came to sit in the same
    repository, both correct.
    """
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q"],
        cwd=ROOT, capture_output=True, text=True, check=False,
        env={"MEMLAB_LLM": "fake", "PATH": "/usr/bin:/bin", "HOME": str(pathlib.Path.home())},
    )
    cases = 0
    for line in proc.stdout.splitlines():
        if line.strip().endswith("collected") or " tests collected" in line:
            head = line.strip().split()[0]
            if head.isdigit():
                cases = int(head)
    if not cases:
        raise SystemExit(
            "build_site_data: could not read a test count from pytest --collect-only.\n"
            + (proc.stdout or proc.stderr)[-800:]
        )
    functions = sum(
        path.read_text().count("\ndef test_")
        for path in [
            *(ROOT / "curriculum").rglob("lab/test_lab.py"),
            *(ROOT / "capstone" / "tests").glob("test_*.py"),
        ]
    )
    return {
        "cases": cases,
        "functions": functions,
        "definition": "cases collected by pytest; functions are `def test_` definitions",
    }


def build() -> dict:
    syl = syllabus()
    graph = json.loads(GRAPH.read_text())
    nodes = {n["id"]: n for n in graph["nodes"]}
    meta = {d.meta["id"]: d.meta for d in lessons()}
    concept_docs = {d.meta["id"]: d.meta for d in concepts()}

    level_title = {lv["id"]: lv["title"] for lv in syl["levels"]}
    module_of = {}
    modules = []
    for lv in syl["levels"]:
        for i, mod in enumerate(lv["modules"], start=1):
            modules.append({
                "id": mod["id"],
                "title": mod["title"],
                "level": lv["id"],
                "level_title": lv["title"],
                "question": lv["question"],
                "index": i,
                "total": len(lv["modules"]),
                "lessons": [le["id"] for le in mod["lessons"]],
                "path": f"modules/{mod['id']}/index.md",
            })
            module_of[mod["id"]] = modules[-1]

    flat = list(syllabus_lessons(syl))
    rows = []
    for order, (level, module, entry) in enumerate(flat):
        m = meta.get(entry["id"], {})
        piece = m.get("capstone_piece")
        mod = module_of[module]
        within = mod["lessons"].index(entry["id"]) + 1
        rows.append({
            "id": entry["id"],
            "title": entry["title"],
            "level": level,
            "level_title": level_title[level],
            "module": module,
            "module_title": mod["title"],
            "module_index": mod["index"],
            "module_total": mod["total"],
            "in_module": within,
            "of_module": len(mod["lessons"]),
            "stage": entry["stage"],
            "order": order,
            # 1-based, matching the "#" column SYLLABUS.md already prints --
            # the only place a learner can currently find their position.
            "position": order + 1,
            "minutes": m.get("estimated_minutes", 0),
            "objective": entry["objective"],
            "path": f"curriculum/{level}/{entry['id']}/index.md",
            "lab": f"curriculum/{level}/{entry['id']}/lab/lab.py" if m.get("lab") else None,
            "capstone_piece": [piece] if isinstance(piece, str) else (piece or []),
        })

    # Sequence is the whole point of this milestone, so it is computed here
    # once rather than left to each surface to re-derive.
    for i, r in enumerate(rows):
        r["prev"] = {"id": rows[i - 1]["id"], "title": rows[i - 1]["title"],
                     "path": rows[i - 1]["path"]} if i else None
        r["next"] = ({"id": rows[i + 1]["id"], "title": rows[i + 1]["title"],
                      "path": rows[i + 1]["path"]} if i + 1 < len(rows) else None)

    by_id = {r["id"]: r for r in rows}
    for mod in modules:
        ls = [by_id[i] for i in mod["lessons"]]
        mod["minutes"] = sum(x["minutes"] for x in ls)
        mod["hours"] = round(mod["minutes"] / 60, 1)
        mod["first"] = ls[0]["path"]
        mod["count"] = len(ls)

    # Reverse indices. build_graph.py computes these in memory but serialises
    # only nodes and edges, so they are recomputed here rather than shared.
    taught_in: dict[str, list[str]] = {}
    used_in: dict[str, list[str]] = {}
    contrasts: dict[str, list[str]] = {}
    for e in graph["edges"]:
        if e["kind"] == "teaches":
            taught_in.setdefault(e["to"], []).append(e["from"])
        elif e["kind"] == "uses":
            used_in.setdefault(e["to"], []).append(e["from"])
        elif e["kind"] == "contrasts_with":
            contrasts.setdefault(e["from"], []).append(e["to"])
            contrasts.setdefault(e["to"], []).append(e["from"])

    by_level = {lv["id"]: 0 for lv in syl["levels"]}
    minutes_by_level = dict.fromkeys(by_level, 0)
    by_stage = dict.fromkeys(syl["stages"], 0)
    for r in rows:
        by_level[r["level"]] += 1
        minutes_by_level[r["level"]] += r["minutes"]
        by_stage[r["stage"]] += 1

    concept_rows = []
    for cid, cmeta in sorted(concept_docs.items()):
        node = nodes.get(cid, {})
        t, u = sorted(taught_in.get(cid, [])), sorted(used_in.get(cid, []))
        concept_rows.append({
            "id": cid,
            "title": cmeta.get("title", cid),
            "stage": cmeta.get("stage", node.get("stage", "")),
            "path": f"concepts/{cid}.md",
            "taught_in": t,
            "used_in": u,
            "contrasts_with": sorted(set(contrasts.get(cid, []))),
            "touches": len(t) + len(u),
        })

    total_minutes = sum(r["minutes"] for r in rows)
    n = len(rows)
    write_path = sum(by_stage[s] for s in WRITE_PATH_STAGES)
    kinds: dict[str, int] = {}
    for e in graph["edges"]:
        kinds[e["kind"]] = kinds.get(e["kind"], 0) + 1

    return {
        "generated_by": "tools/build_site_data.py",
        "course": {"title": syl["title"], "tagline": syl["tagline"]},
        "stats": {
            "lessons": n,
            "modules": len(modules),
            "concepts": len(concept_rows),
            "minutes": total_minutes,
            "hours": round(total_minutes / 60, 1),
            "labs": sum(1 for d in lessons() if d.meta.get("lab")),
            "labs_offline": sum(1 for d in lessons() if d.meta.get("lab_runtime") == "fake"),
            "levels": [
                {
                    "id": lv["id"],
                    "title": lv["title"],
                    "question": lv["question"],
                    "outcome": " ".join(lv["outcome"].split()),
                    "lessons": by_level[lv["id"]],
                    "hours": round(minutes_by_level[lv["id"]] / 60, 1),
                }
                for lv in syl["levels"]
            ],
            "stages": [{"id": s, "lessons": by_stage[s]} for s in syl["stages"]],
            "graph": {
                "nodes": len(graph["nodes"]),
                "edges": len(graph["edges"]),
                "by_kind": dict(sorted(kinds.items())),
                "lesson_concept_edges": kinds.get("uses", 0) + kinds.get("teaches", 0),
            },
            "tests": _test_counts(),
            "thesis": {
                "write_path_stages": list(WRITE_PATH_STAGES),
                "write_path_lessons": write_path,
                "write_path_pct": round(100 * write_path / n),
                "retrieve_lessons": by_stage["retrieve"],
                "retrieve_pct": round(100 * by_stage["retrieve"] / n),
            },
            "hub_threshold": 5,
            "hubs_at_threshold": sum(1 for c in concept_rows if c["touches"] >= 5),
            "concepts_touched_once": sum(1 for c in concept_rows if c["touches"] == 1),
        },
        "lessons": rows,
        "modules": modules,
        "concepts": concept_rows,
        "hubs": [
            {"id": c["id"], "title": c["title"], "touches": c["touches"]}
            for c in sorted(concept_rows, key=lambda c: (-c["touches"], c["title"]))[:12]
        ],
    }


def render_hero(d: dict) -> str:
    """The home hero, as static HTML. Every number here is `d`, never a literal."""
    s, th = d["stats"], d["stats"]["thesis"]
    s_lessons = s["lessons"]
    peak = max(x["lessons"] for x in s["stages"]) or 1
    bars = []
    for stage in s["stages"]:
        pct = 100 * stage["lessons"] / peak
        tone = ("wp" if stage["id"] in th["write_path_stages"]
                else "rd" if stage["id"] == "retrieve" else "sd")
        bars.append(
            f'      <div class="mem-bar mem-bar--{tone}">'
            f'<span class="mem-bar__name">{stage["id"]}</span>'
            f'<span class="mem-bar__track"><span class="mem-bar__fill"'
            f' style="width: {pct:.1f}%"></span></span>'
            f'<span class="mem-bar__n">{stage["lessons"]}</span></div>'
        )
    wp = ", ".join(th["write_path_stages"][:-1]) + " + " + th["write_path_stages"][-1]
    stats = [
        (str(s["lessons"]), "lessons"),
        (f'{s["hours"]}<span class="mem-stat__unit">h</span>', "of material"),
        (str(s["tests"]["cases"]), "tests green"),
        ("0", "API keys"),
    ]
    tiles = "".join(
        f'<div class="mem-stat"><div class="mem-stat__n">{v}</div>'
        f'<div class="mem-stat__l">{label}</div></div>'
        for v, label in stats
    )
    # One primary action, named in the units of the thing a person is about
    # to do. "84 lessons, 60.9 hours" is true and is the reason the page read
    # as overwhelming; the first module is four lessons and about two hours.
    m0 = d["modules"][0]
    first = next(r for r in d["lessons"] if r["id"] == m0["lessons"][0])
    cta = (
        f'      <a class="mem-cta" href="{{{{ base_url }}}}/{first["path"].replace("index.md", "")}">\n'
        f'        <span class="mem-cta__l">start here</span>\n'
        f'        <span class="mem-cta__t">{first["title"]}</span>\n'
        f'        <span class="mem-cta__d">First of {m0["count"]} lessons in '
        f'<b>{m0["title"]}</b> &mdash; about {m0["hours"]} hours. '
        f'You will see a retrieval pipeline rank the right answer 18th, and know why.</span>\n'
        f'      </a>\n'
    )
    secondary = (
        '      <p class="mem-second">Know what you are looking for? '
        '<a href="{{ base_url }}/map/">Browse all '
        f'{s_lessons} lessons</a> or read the '
        '<a href="{{ base_url }}/SYLLABUS/">full syllabus</a>.</p>\n'
    )
    return f"""{BEGIN}
<section class="mem-hero">
  <p class="mem-hero__kicker">{s["lessons"]} lessons &middot; {len(s["levels"])} levels
    &middot; {s["hours"]} hours &middot; every lab runs offline</p>
  <h1 class="mem-hero__h1">{d["course"]["title"]}</h1>
  <p class="mem-hero__tag"><span aria-hidden="true">&gt;</span>
    {d["course"]["tagline"]}</p>

  <div class="mem-hero__grid">
    <figure class="mem-chart">
      <figcaption>
        <span class="mem-chart__title">where the course actually spends its time</span>
        <span class="mem-chart__sub">lessons per pipeline stage</span>
      </figcaption>
{chr(10).join(bars)}
      <p class="mem-chart__read"><b>{wp}</b> hold {th["write_path_lessons"]} of
        {s["lessons"]} lessons &mdash; <b>{th["write_path_pct"]}%</b>.
        <b class="mem-rd">retrieve</b> holds {th["retrieve_lessons"]} &mdash;
        <b>{th["retrieve_pct"]}%</b>.</p>
    </figure>

    <div class="mem-ways">
      <div class="mem-resume" hidden><span class="mem-resume__l">continue</span>
        <a class="mem-resume__a" href="#"></a></div>
{cta}{secondary}      <div class="mem-stats">{tiles}</div>
    </div>
  </div>
</section>
{END}
"""


def render_strip(d: dict) -> str:
    """A Jinja lookup, keyed by src_uri, that main.html renders on lesson pages.

    Build-time rather than a runtime fetch, for the same reason the hero is:
    "lesson 7 of 84" has to be on the page at first paint and with JavaScript
    off. It is a template because the alternative -- writing position into the
    lesson markdown -- would edit the course, which this milestone may not do.

    No `null` anywhere: Jinja spells it `none`, so JSON nulls would not parse.
    Absent prev/next are empty objects instead.
    """
    def link(x):
        return {"title": x["title"], "url": x["path"].replace("index.md", "")} if x else {}

    table = {
        r["path"]: {
            "level": r["level"],
            "level_title": r["level_title"],
            "module_title": r["module_title"],
            "module_index": r["module_index"],
            "module_total": r["module_total"],
            "module_url": f"modules/{r['module']}/",
            "position": r["position"],
            "total": len(d["lessons"]),
            "minutes": r["minutes"],
            "lab": r["lab"] or "",
            "id": r["id"],
            "prev": link(r["prev"]),
            "next": link(r["next"]),
        }
        for r in d["lessons"]
    }
    return (
        f"{BEGIN}\n"
        "{% set MEM_LESSON = "
        + json.dumps(table, indent=1, sort_keys=True)
        + " %}\n" + END + "\n"
    )


def render_module_pages(d: dict) -> dict[pathlib.Path, str]:
    """One page per module -- the unit that turns 84 lessons into a short list.

    Labelled in hours, never "a sitting": modules measure 1.8 to 4.7 hours, so
    promising one evening would be false for most of them.
    """
    by_id = {r["id"]: r for r in d["lessons"]}
    out = {}
    for mod in d["modules"]:
        rows = [by_id[i] for i in mod["lessons"]]
        lines = [
            f"# {mod['title']}",
            "",
            f"*{mod['question']}*",
            "",
            (f"Module {mod['index']} of {mod['total']} in **{mod['level_title']}** "
             f"&middot; {mod['count']} lessons &middot; about {mod['hours']} hours"),
            "",
        ]
        for r in rows:
            # A list, not a table: in the site's content column a four-column
            # table squeezes lesson titles to one word per line.
            lines += [
                (f"**{r['position']}. [{r['title']}](../../{r['path']})**"
                 f" &middot; ~{r['minutes']} min"),
                "",
                f"{r['objective']}",
                "",
            ]
        lines += [
            f"[Start with {rows[0]['title']} &rarr;](../../{rows[0]['path']})",
            "",
        ]
        out[MODULES_DIR / mod['id'] / "index.md"] = "\n".join(lines)
    return out


def render_roadmap(d: dict) -> str:
    """The whole course as one rail, because the course is one line.

    The ask was for something roadmap.sh-shaped. The honest version here is a
    spine, not a web: all 83 prerequisite edges have in-degree and out-degree
    exactly 1, so there is exactly one order and a branching graph would be a
    lie about the material.

    HTML boxes rather than a drawn graph, for the reason roadmap.sh itself gets
    wrong -- its nodes are absolutely positioned with no edge model, so nothing
    reflows and a phone gets a pinch-zoom canvas. A rail made of CSS is legible
    at 400px and 1200px, needs no JavaScript to render, and no CDN.

    Every number comes from `d`. `progress.js` may later tint a stop it knows
    is finished; nothing here depends on that having happened.
    """
    bands = []
    for lv in d["stats"]["levels"]:
        mods = [m for m in d["modules"] if m["level"] == lv["id"]]
        stops = "".join(
            f'      <a class="mem-road__stop" href="{{{{ base_url }}}}/{m["path"].replace("index.md", "")}"'
            f' data-module="{m["id"]}">'
            f'<span class="mem-road__n">{m["index"]:02d}</span>'
            f'<span class="mem-road__body"><span class="mem-road__t">{m["title"]}</span>'
            f'<span class="mem-road__meta">{m["count"]} lessons &middot; {m["hours"]} h</span>'
            f'</span></a>\n'
            for m in mods
        )
        bands.append(
            f'  <section class="mem-road__band" data-level="{lv["id"]}">\n'
            f'    <header class="mem-road__head">\n'
            f'      <span class="mem-lv" data-level="{lv["id"]}">{lv["id"]}</span>\n'
            f'      <h3 class="mem-road__lvl">{lv["title"]}</h3>\n'
            f'      <p class="mem-road__q">{lv["question"]}</p>\n'
            f'      <span class="mem-road__count">{len(mods)} modules &middot; '
            f'{lv["lessons"]} lessons &middot; {lv["hours"]} h</span>\n'
            f'    </header>\n'
            f'    <div class="mem-road__stops">\n{stops}    </div>\n'
            f'  </section>\n'
        )

    total_modules = d["stats"]["modules"]
    return f"""{BEGIN}
<section class="mem-road mem-full" aria-label="The whole course, in order">
  <p class="mem-lbl">the whole path &middot; {total_modules} modules &middot; {d["stats"]["hours"]} hours</p>
  <p class="mem-road__legend">Read top to bottom &mdash; each module depends on the
    one above it, so there is only ever one next thing. A stop you have finished
    is ticked. <b>Numbers are the module's own lessons and hours</b>, not a
    running total.</p>
{"".join(bands)}</section>
{END}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if output is stale")
    args = ap.parse_args()

    payload = build()
    data = json.dumps(payload, indent=2) + "\n"
    hero = render_hero(payload)
    strip = render_strip(payload)
    road = render_roadmap(payload)
    module_pages = render_module_pages(payload)

    if args.check:
        wanted = [(DATA_OUT, data), (HERO_OUT, hero), (STRIP_OUT, strip),
                  (ROAD_OUT, road)]
        wanted += sorted(module_pages.items())
        stale = [
            str(p.relative_to(ROOT))
            for p, want in wanted
            if not p.exists() or p.read_text() != want
        ]
        extra = sorted(
            str(p.relative_to(ROOT)) for p in MODULES_DIR.glob("*/index.md")
            if p not in module_pages
        ) if MODULES_DIR.exists() else []
        stale += [f"{e} (no longer a module)" for e in extra]
        if stale:
            print(
                "stale site data: " + ", ".join(stale)
                + " -- run tools/build_site_data.py",
                file=sys.stderr,
            )
            return 1
        print("site data up to date")
        return 0

    for p, want in [(DATA_OUT, data), (HERO_OUT, hero), (STRIP_OUT, strip),
                    (ROAD_OUT, road)] + sorted(
        module_pages.items()
    ):
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(want)
    if MODULES_DIR.exists():
        for orphan in MODULES_DIR.glob("*/index.md"):
            if orphan not in module_pages:
                orphan.unlink()
                orphan.parent.rmdir()
    st = payload["stats"]
    print(
        f"site data: {st['lessons']} lessons, {st['concepts']} concepts, "
        f"{st['tests']['cases']} tests, {st['modules']} module pages, "
        f"thesis {st['thesis']['write_path_pct']}% vs {st['thesis']['retrieve_pct']}%"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
