#!/usr/bin/env python3
"""Generate the data the site's interactive pages render, and the home hero.

The landing page, the course map and the concept atlas all display figures --
how many lessons sit in each stage, how long the course is, which concepts
recur. Every one of those is a countable property of `syllabus.yml`, the lesson
frontmatter and `concepts/graph.json`, so none of them may be typed into a
template or a script. This is the fourth generated view of the course, after
SYLLABUS.md, the graph blocks and the mkdocs nav.

Two outputs, both committed and both covered by --check:

  docs/assets/data/site.json          read by the map and atlas at runtime
  overrides/partials/hero-stats.html  included by main.html at BUILD time

The hero is a rendered partial rather than a client-side fetch on purpose. Its
whole job is to show the thesis -- half the course is evolve and govern, a ninth
is retrieve -- and a number that flashes in after paint, or is missing entirely
without JavaScript, is not showing it.

    uv run python tools/build_site_data.py            # write both
    uv run python tools/build_site_data.py --check    # fail if either is stale
"""
from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from _common import ROOT, concepts, lessons, syllabus, syllabus_lessons  # noqa: E402

GRAPH = ROOT / "concepts" / "graph.json"
DATA_OUT = ROOT / "docs" / "assets" / "data" / "site.json"
HERO_OUT = ROOT / "overrides" / "partials" / "hero-stats.html"

BEGIN = "<!-- site:begin -- generated by tools/build_site_data.py -->"
END = "<!-- site:end -->"

# The stages whose share of the course *is* the argument the course makes.
WRITE_PATH_STAGES = ("evolve", "govern")
# A concept is "touched" by a lesson that teaches it or uses it. Counting only
# `uses` undercounts every concept by its own home lesson.
TOUCH_KINDS = ("teaches", "uses")


def _test_counts() -> dict:
    """Two honest numbers, because they answer different questions.

    `functions` counts `def test_` in the tree. `cases` is what pytest actually
    runs, which is larger because parametrised tests expand. Quoting one while
    meaning the other is how "823 tests" and "757 tests" came to sit in the same
    repository, both correct.
    """
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q"],
        cwd=ROOT, capture_output=True, text=True, check=False,
        env={"MEMLAB_LLM": "fake", "PATH": "/usr/bin:/bin", "HOME": str(pathlib.Path.home())},
    )
    cases = 0
    for line in proc.stdout.splitlines():
        if line.strip().endswith("collected") or " tests collected" in line:
            head = line.strip().split()[0]
            if head.isdigit():
                cases = int(head)
    if not cases:
        raise SystemExit(
            "build_site_data: could not read a test count from pytest --collect-only.\n"
            + (proc.stdout or proc.stderr)[-800:]
        )
    functions = sum(
        path.read_text().count("\ndef test_")
        for path in [
            *(ROOT / "curriculum").rglob("lab/test_lab.py"),
            *(ROOT / "capstone" / "tests").glob("test_*.py"),
        ]
    )
    return {
        "cases": cases,
        "functions": functions,
        "definition": "cases collected by pytest; functions are `def test_` definitions",
    }


def build() -> dict:
    syl = syllabus()
    graph = json.loads(GRAPH.read_text())
    nodes = {n["id"]: n for n in graph["nodes"]}
    meta = {d.meta["id"]: d.meta for d in lessons()}
    concept_docs = {d.meta["id"]: d.meta for d in concepts()}

    rows = []
    for order, (level, module, entry) in enumerate(syllabus_lessons(syl)):
        m = meta.get(entry["id"], {})
        piece = m.get("capstone_piece")
        rows.append({
            "id": entry["id"],
            "title": entry["title"],
            "level": level,
            "module": module,
            "stage": entry["stage"],
            "order": order,
            "minutes": m.get("estimated_minutes", 0),
            "objective": entry["objective"],
            "path": f"curriculum/{level}/{entry['id']}/index.md",
            "capstone_piece": [piece] if isinstance(piece, str) else (piece or []),
        })

    # Reverse indices. build_graph.py computes these in memory but serialises
    # only nodes and edges, so they are recomputed here rather than shared.
    taught_in: dict[str, list[str]] = {}
    used_in: dict[str, list[str]] = {}
    contrasts: dict[str, list[str]] = {}
    for e in graph["edges"]:
        if e["kind"] == "teaches":
            taught_in.setdefault(e["to"], []).append(e["from"])
        elif e["kind"] == "uses":
            used_in.setdefault(e["to"], []).append(e["from"])
        elif e["kind"] == "contrasts_with":
            contrasts.setdefault(e["from"], []).append(e["to"])
            contrasts.setdefault(e["to"], []).append(e["from"])

    by_level = {lv["id"]: 0 for lv in syl["levels"]}
    minutes_by_level = dict.fromkeys(by_level, 0)
    by_stage = dict.fromkeys(syl["stages"], 0)
    for r in rows:
        by_level[r["level"]] += 1
        minutes_by_level[r["level"]] += r["minutes"]
        by_stage[r["stage"]] += 1

    concept_rows = []
    for cid, cmeta in sorted(concept_docs.items()):
        node = nodes.get(cid, {})
        t, u = sorted(taught_in.get(cid, [])), sorted(used_in.get(cid, []))
        concept_rows.append({
            "id": cid,
            "title": cmeta.get("title", cid),
            "stage": cmeta.get("stage", node.get("stage", "")),
            "path": f"concepts/{cid}.md",
            "taught_in": t,
            "used_in": u,
            "contrasts_with": sorted(set(contrasts.get(cid, []))),
            "touches": len(t) + len(u),
        })

    total_minutes = sum(r["minutes"] for r in rows)
    n = len(rows)
    write_path = sum(by_stage[s] for s in WRITE_PATH_STAGES)
    kinds: dict[str, int] = {}
    for e in graph["edges"]:
        kinds[e["kind"]] = kinds.get(e["kind"], 0) + 1

    return {
        "generated_by": "tools/build_site_data.py",
        "course": {"title": syl["title"], "tagline": syl["tagline"]},
        "stats": {
            "lessons": n,
            "concepts": len(concept_rows),
            "minutes": total_minutes,
            "hours": round(total_minutes / 60, 1),
            "labs": sum(1 for d in lessons() if d.meta.get("lab")),
            "labs_offline": sum(1 for d in lessons() if d.meta.get("lab_runtime") == "fake"),
            "levels": [
                {
                    "id": lv["id"],
                    "title": lv["title"],
                    "question": lv["question"],
                    "outcome": " ".join(lv["outcome"].split()),
                    "lessons": by_level[lv["id"]],
                    "hours": round(minutes_by_level[lv["id"]] / 60, 1),
                }
                for lv in syl["levels"]
            ],
            "stages": [{"id": s, "lessons": by_stage[s]} for s in syl["stages"]],
            "graph": {
                "nodes": len(graph["nodes"]),
                "edges": len(graph["edges"]),
                "by_kind": dict(sorted(kinds.items())),
                "lesson_concept_edges": kinds.get("uses", 0) + kinds.get("teaches", 0),
            },
            "tests": _test_counts(),
            "thesis": {
                "write_path_stages": list(WRITE_PATH_STAGES),
                "write_path_lessons": write_path,
                "write_path_pct": round(100 * write_path / n),
                "retrieve_lessons": by_stage["retrieve"],
                "retrieve_pct": round(100 * by_stage["retrieve"] / n),
            },
            "hub_threshold": 5,
            "hubs_at_threshold": sum(1 for c in concept_rows if c["touches"] >= 5),
            "concepts_touched_once": sum(1 for c in concept_rows if c["touches"] == 1),
        },
        "lessons": rows,
        "concepts": concept_rows,
        "hubs": [
            {"id": c["id"], "title": c["title"], "touches": c["touches"]}
            for c in sorted(concept_rows, key=lambda c: (-c["touches"], c["title"]))[:12]
        ],
    }


def render_hero(d: dict) -> str:
    """The home hero, as static HTML. Every number here is `d`, never a literal."""
    s, th = d["stats"], d["stats"]["thesis"]
    peak = max(x["lessons"] for x in s["stages"]) or 1
    bars = []
    for stage in s["stages"]:
        pct = 100 * stage["lessons"] / peak
        tone = ("wp" if stage["id"] in th["write_path_stages"]
                else "rd" if stage["id"] == "retrieve" else "sd")
        bars.append(
            f'      <div class="mem-bar mem-bar--{tone}">'
            f'<span class="mem-bar__name">{stage["id"]}</span>'
            f'<span class="mem-bar__track"><span class="mem-bar__fill"'
            f' style="width: {pct:.1f}%"></span></span>'
            f'<span class="mem-bar__n">{stage["lessons"]}</span></div>'
        )
    wp = ", ".join(th["write_path_stages"][:-1]) + " + " + th["write_path_stages"][-1]
    stats = [
        (str(s["lessons"]), "lessons"),
        (f'{s["hours"]}<span class="mem-stat__unit">h</span>', "of material"),
        (str(s["tests"]["cases"]), "tests green"),
        ("0", "API keys"),
    ]
    tiles = "".join(
        f'<div class="mem-stat"><div class="mem-stat__n">{v}</div>'
        f'<div class="mem-stat__l">{label}</div></div>'
        for v, label in stats
    )
    paths = [
        ("Thirty minutes",
         "Run one lab and read <code>memory-is-not-rag</code>. That is the whole "
         "argument, demonstrated rather than asserted."),
        ("Front to back",
         "The syllabus is the order, and CI proves it is a valid topological sort of "
         "the prerequisite graph &mdash; nothing depends on something you have not met."),
        ("Straight at your bug",
         "Scan the map for the failure you are actually hitting &mdash; a stale belief, "
         "a duplicate, a leak that survived deletion."),
    ]
    cards = "".join(
        f'      <a class="mem-path" href="{href}"><span class="mem-path__n">{i:02d}</span>'
        f'<span><span class="mem-path__t">{t}</span>'
        f'<span class="mem-path__d">{body}</span></span></a>\n'
        # Raw HTML in a template, so mkdocs never rewrites these the way it
        # rewrites .md links in Markdown -- they are built URLs, and base_url
        # is what keeps them correct under the /Mem-101/ subpath.
        for i, ((t, body), href) in enumerate(
            zip(paths, ["{{ base_url }}/curriculum/beginner/memory-is-not-rag/",
                        "{{ base_url }}/SYLLABUS/", "{{ base_url }}/map/"]), start=1)
    )
    return f"""{BEGIN}
<section class="mem-hero">
  <p class="mem-hero__kicker">{s["lessons"]} lessons &middot; {len(s["levels"])} levels
    &middot; {s["hours"]} hours &middot; every lab runs offline</p>
  <h1 class="mem-hero__h1">{d["course"]["title"]}</h1>
  <p class="mem-hero__tag"><span aria-hidden="true">&gt;</span>
    {d["course"]["tagline"]}</p>

  <div class="mem-hero__grid">
    <figure class="mem-chart">
      <figcaption>
        <span class="mem-chart__title">where the course actually spends its time</span>
        <span class="mem-chart__sub">lessons per pipeline stage</span>
      </figcaption>
{chr(10).join(bars)}
      <p class="mem-chart__read"><b>{wp}</b> hold {th["write_path_lessons"]} of
        {s["lessons"]} lessons &mdash; <b>{th["write_path_pct"]}%</b>.
        <b class="mem-rd">retrieve</b> holds {th["retrieve_lessons"]} &mdash;
        <b>{th["retrieve_pct"]}%</b>.</p>
    </figure>

    <div class="mem-ways">
      <p class="mem-chart__title">three ways in</p>
{cards}      <div class="mem-stats">{tiles}</div>
    </div>
  </div>
</section>
{END}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if output is stale")
    args = ap.parse_args()

    payload = build()
    data = json.dumps(payload, indent=2) + "\n"
    hero = render_hero(payload)

    if args.check:
        stale = [
            str(p.relative_to(ROOT))
            for p, want in ((DATA_OUT, data), (HERO_OUT, hero))
            if not p.exists() or p.read_text() != want
        ]
        if stale:
            print(
                "stale site data: " + ", ".join(stale)
                + " -- run tools/build_site_data.py",
                file=sys.stderr,
            )
            return 1
        print("site data up to date")
        return 0

    for p, want in ((DATA_OUT, data), (HERO_OUT, hero)):
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(want)
    st = payload["stats"]
    print(
        f"site data: {st['lessons']} lessons, {st['concepts']} concepts, "
        f"{st['tests']['cases']} tests, thesis {st['thesis']['write_path_pct']}%"
        f" vs {st['thesis']['retrieve_pct']}%"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
