"""Write mkdocs' nav from syllabus.yml, so ordering has one source of truth.

`curriculum/syllabus.yml` decides linear order and `SYLLABUS.md` is generated
from it. The site's navigation is a third view of the same list, and hand
maintaining it would make reordering the course a two-file edit that nobody
would remember to do twice.

    uv run python tools/render_nav.py            # rewrite the block
    uv run python tools/render_nav.py --check    # fail if it is stale

The block is delimited the same way the graph regions are, so the rest of
mkdocs.yml stays hand-written.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _common import syllabus

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "mkdocs.yml"
BEGIN = "  # nav:begin -- generated by tools/render_nav.py\n"
END = "  # nav:end\n"


def _concepts() -> list[str]:
    return sorted(p.name for p in (ROOT / "concepts").glob("*.md"))


def build() -> str:
    out = [BEGIN]
    for level in syllabus()["levels"]:
        out.append(f"  - {level['title']}:\n")
        for module in level["modules"]:
            out.append(f"    - {module['title']}:\n")
            # First child, which is what navigation.indexes turns into the
            # section's own page -- a module header used to be a dead label.
            overview = f"modules/{module['id']}/index.md"
            if (ROOT / overview).exists():
                out.append(f"      - {overview}\n")
            for lesson in module["lessons"]:
                path = f"curriculum/{level['id']}/{lesson['id']}/index.md"
                if (ROOT / path).exists():
                    out.append(f"      - {lesson['title']}: {path}\n")
    out.append("  - Concepts:\n")
    out.extend(f"    - concepts/{name}\n" for name in _concepts())
    out.append("  - Landscape:\n")
    out.append("    - landscape/index.md\n")
    for page in sorted((ROOT / "landscape").rglob("*.md")):
        rel = page.relative_to(ROOT)
        if rel.name != "index.md":
            out.append(f"    - {rel}\n")
    out.append(END)
    return "".join(out)


def main() -> int:
    text = CONFIG.read_text()
    start, end = text.index(BEGIN), text.index(END) + len(END)
    fresh = text[:start] + build() + text[end:]
    if "--check" in sys.argv:
        if fresh != text:
            print("  FAIL mkdocs.yml nav is stale -- run tools/render_nav.py")
            return 1
        print("  ok   render_nav.py")
        return 0
    CONFIG.write_text(fresh)
    print("  ok   render_nav.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
